version: "3.9"
services:
  dockle-lint:
    image: dockle-lint:$TAG
    build: .
    container_name: dockle-lint
    env_file:
      - .env
    ports:
      - 8080:8080
    secrets:
      - passwd

secrets:
  passwd:
    file: ./passwd.txt